zenodo_url: "https://zenodo.org/record/8208151/files"
dataset: "Amazon0601_0.csv"
dataset_meta: "Amazon0601_0.csv.meta"
iterations: 10
scheduling_policies:
  - STATIC
  # - SS
  - GSS
  - TSS
  - FAC2
  - TFSS
  - FISS
  - VISS
  - PLS
  - MSTATIC
  - MFSC
  - PSS
eval_cst:
  threads:
    - 2
    - 4
    - 8
  task_size:
    start: 10
    end:   100000
    step:  10000
max_threads: 8
min_threads: 4
